# Generated by Django 4.0.5 on 2022-06-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0002_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='location',
            field=models.CharField(default='Kenya', max_length=100),
        ),
    ]
