# Generated by Django 4.0.5 on 2022-06-14 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0005_alter_rating_project_alter_rating_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(null=True, upload_to='profile'),
        ),
    ]
